name: cpp_quiz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - jinja2
  - pydantic
  - rich
  - pip:
    - pydantic-settings
    - langchain-core
    - langchain-google-genai
    - rank-bm25
    - typing
    - markdown2